name: "Knative Service Deploy"
description: "Creating Knative Services using kn"
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  service_name:
    description: "The Knative Service Name"
    required: true
  service_namespace:
    description: "The Kubernetes Namespace to deploy to. Defaults to current context's namespace."
    required: false
  service_operation:
    description: "The Knative Service Operation"
    required: false
    default: "create"
  container_image:
    description: "The Knative Service Image"
    required: true
  service_params:
    description: "The extra parameter to pass to service"
    required: false
  registry_user:
    description: "The registry user to use to create image pull secret"
    required: false
  registry_password:
    description: "The registry user password"
    required: false
outputs:
  service_url:
    description: "The Knative Service URL"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.service_name }}
    - ${{ inputs.service_namespace }}
    - ${{ inputs.service_operation }}
    - ${{ inputs.container_image }}
    - ${{ inputs.service_params }}
    - ${{ inputs.registry_user }}
    - ${{ inputs.registry_password }}
