name: Create Knative service
on: [ push, workflow_dispatch ]
env:
  IMAGE_REGISTRY: "quay.io"
  REGISTRY_USERNAME: "diagrawa"
  REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"
  IMAGE_NAME: "getting-started-knative"
  BASE_IMAGE: "registry.access.redhat.com/ubi8/openjdk-11"
  PROJECT_DIR: "getting-started-knative"
  TARGET_DIR: target/
  MVN_REPO_DIR: ~/.m2/repository

jobs:
  checkout-and-build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      # Checkout project repository
      - name: Checkout example repository
        uses: actions/checkout@v2
        with:
          repository: redhat-actions/quarkus-quickstarts

      # If none of these files has changed, we assume that the contents of
      # .m2/repository can be fetched from the cache.
      - name: Hash Maven files
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          echo "MVN_HASH=${{ hashFiles('**/pom.xml', '.mvn/**/*', 'mvnw*') }}" >> $GITHUB_ENV

      # Download the m2 repository from the cache to speed up the build.
      - name: Check for Maven cache
        id: check_mvn_cache
        uses: actions/cache@v2
        with:
          path: ${{ env.MVN_REPO_DIR }}
          key: ${{ env.MVN_HASH }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Build
        id: build_app
        working-directory: ${{ env.PROJECT_DIR }}
        run: mvn -B -DskipTests clean package --file pom.xml

      # If there was no cache hit above, store the output into the cache now.
      - name: Save Maven repo into cache
        if: ${{ steps.check_mvn_cache.outputs.cache-hit }} != 'true'
        uses: actions/cache@v2
        with:
          path: ${{ env.MVN_REPO_DIR }}
          key: ${{ env.MVN_HASH }}

      #  Store the output jar into the env for reuse below.
      - name: Get jar filename
        run: |
          export JAR_NAME="$(basename $(ls ${{ env.PROJECT_DIR }}/target/*.jar))"
          echo "${{ env.PROJECT_DIR }} App jar is $JAR_NAME"
          echo "::set-output name=jarname::$JAR_NAME"
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

      # Upload the source code for future jobs to use.
      - name: Upload working directory
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_DIR }}
          path: ./
          if-no-files-found: error

  build-and-deploy-images:
    name: Deploy Knative Service
    runs-on: ubuntu-20.04
    needs: [ checkout-and-build ]
    steps:

      # Checkout Knative service deploy action github repository
      - name: Checkout Knative service deploy action
        uses: actions/checkout@v2
        with:
          path: "kn-service-manager"

      - name: Download working directory
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PROJECT_DIR }}

      - name: Get Commit Metadata
        uses: redhat-actions/common/commit-data@v1
        id: commit_metadata

      # Build container image using Buildah Action
      - name: Build Image
        id: buildah_build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: "${{ steps.commit_metadata.outputs.branch }}-${{ steps.commit_metadata.outputs.short_sha }}"
          base-image: ${{ env.BASE_IMAGE }}
          context: ${{ env.PROJECT_DIR }}
          dockerfiles: |
            ./${{ env.PROJECT_DIR }}/src/main/docker/Dockerfile.jvm

      - name: Push To Quay
        id: push_tag_to_quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.buildah_build.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USERNAME }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Login into OpenShift Cluster
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: diagrawa-code

      - name: Deploy Knative Service
        id: kn_service_deploy
        uses: ./kn-service-manager/
        with:
          service_name: ${{ env.IMAGE_NAME }}
          container_image: "${{ steps.push_tag_to_quay.outputs.registry-path }}"

      - name: Show Kn Service URL
        run: echo ${{ steps.kn_service_deploy.outputs.service_url }}

      # Perform a (very) basic integration test.
      # This step is retried since the time to pull the image and start the pod can vary.
      - name: Test project is running
        uses: nick-invision/retry@v2.2.0
        with:
          timeout_seconds: 3
          retry_wait_seconds: 10
          max_attempts: 10
          warning_on_retry: false
          # Just check that the root endpoint returns a success status (-f flag).
          command: curl -sSfLi ${{ steps.kn_service_deploy.outputs.service_url }}

      # Clean up the resources we deployed, even if there was an error above.
      - name: Delete deployed knative service
        uses: ./kn-service-manager/
        if: always()
        with:
          service_name: ${{ env.IMAGE_NAME }}
          command: delete
