name: App Build and Push(QUAY)
on: [push, workflow_dispatch]
env:
  IMAGE_REGISTRY: "quay.io"
  REGISTRY_USERNAME: "${{ secrets.REGISTRY_USER }}"
  REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"
  IMAGE_NAME: "fruits-app"
  BASE_IMAGE: "registry.access.redhat.com/ubi8/openjdk-11"

jobs:
  checkoutAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v2
        with:
          repository: kameshsampath/kn-service-action-example

      - name: Maven Build
        id: build_app
        run: mvn -B -DskipTests clean package --file pom.xml

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - uses: actions/upload-artifact@v2
        name: Save build target directory
        with:
          name: buildArtifacts
          path: |
            ./**/*
  
  containerBuild:
    runs-on: ubuntu-latest
    needs: [checkoutAndBuild]
    steps:
       - name: Download build target directory
         uses: actions/download-artifact@v2
         with:
          name: buildArtifacts
       - name: Commit Metadata
         id: commit_metadata
         run: |
            echo "##[set-output name=sha;]$(echo $(git rev-parse --short $GITHUB_SHA))"
            echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
       
       - name: Build Image
         uses: redhat-actions/buildah-build@v1
         with:
          # image: "${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}"
          image: ${{ env.IMAGE_NAME }}
          tag: "${{steps.commit_metadata.outputs.branch}}-${{steps.commit_metadata.outputs.sha}}"
          base-image: ${{ env.BASE_IMAGE }}
          dockerfiles: |
            src/main/docker/Dockerfile.jvm

       - name: Push To Quay
         id: push-tag-to-quay
         uses: redhat-actions/push-to-registry@v1
         with:
          image: ${{ env.IMAGE_NAME }}
          tag: "${{steps.commit_metadata.outputs.branch}}-${{steps.commit_metadata.outputs.sha}}"
          registry: ${{ env.IMAGE_REGISTRY }}/${{ secrets.REGISTRY_USER }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

       - name: Login into OpenShift Cluster
         id: oc_login
         uses: redhat-actions/oc-login@v1
         with:
            openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
            openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
            insecure_skip_tls_verify: true
            # openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}

       - name: Knative Service Deploy
         id: kn_service_deploy
         uses: redhat-actions/kn-service-deploy@main
         with: 
           service_name: fruits-app
          #  service_namespace: default
           registry_user: ${{ secrets.REGISTRY_USER }}
           registry_password: ${{ secrets.REGISTRY_PASSWORD }}
           container_image: "${{ steps.push-tag-to-quay.outputs.registry-path }}"
       
       - name: Show Kn Service URL
         run: echo ${{ steps.kn_service_deploy.outputs.service_url }}